### ISSUE TITLE
pgserver Error( error while running server)

### ISSUE THREAD

**Issue by sachinvdrit** [GanuM/profitGuruPOS#756]
- [ ] **the following error we get while running pgserver

**
2017-04-20T01:42:08.701Z - error: Could not start Replication beccause of {"message":"Request error","trace":{"message":"getaddrinfo ENOTFOUND pnyot84dci.execute-api.us-east-1.amazonaws.com pnyot84dci.execute-api.us-east-1.amazonaws.com:443","stack":"Error: getaddrinfo ENOTFOUND pnyot84dci.execute-api.us-east-1.amazonaws.com pnyot84dci.execute-api.us-east-1.amazonaws.com:443\n    at errnoException (dns.js:28:10)\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)","code":"ENOTFOUND","errno":"ENOTFOUND","syscall":"getaddrinfo","hostname":"pnyot84dci.execute-api.us-east-1.amazonaws.com","host":"pnyot84dci.execute-api.us-east-1.amazonaws.com","port":443}}

**Comment by saichaitanyaeruvaram** [comment]
If internet is not there, or API key is changed this error comes.
It is expected.
Contact Chhetry for a demo.

**Comment by sachinvdrit** [comment]
closed
